sudo: false

language: c

os:
  - linux
  - osx

python:
  - "2.6"

compiler:
  - gcc

addons:
  apt:
    packages:
      - libaio-dev
      - libattr1-dev
      - libbrlapi-dev
      - libcap-ng-dev
      - libgcc-4.8-dev
      - libgnutls-dev
      - libgtk-3-dev
      - libiscsi-dev
      - liblttng-ust-dev
      - libncurses5-dev
      - libnfs-dev
      - libnss3-dev
      - libpixman-1-dev
      - libpng12-dev
      - librados-dev
      - libsdl1.2-dev
      - libseccomp-dev
      - libspice-protocol-dev
      - libspice-server-dev
      - libssh2-1-dev
      - liburcu-dev
      - libusb-1.0-0-dev
      - libvte-2.90-dev
      - sparse
      - uuid-dev
      - libsdl2-dev
      - libepoxy-dev

git:
  # we want to do this ourselves
  submodules: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libffi gettext glib pixman pkg-config autoconf pixman sdl2 libepoxy; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./build_macos.sh ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./build_linux.sh ; fi
