environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64

configuration:
  - Release
  - Debug

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor.bat %CONFIGURATION%'

deploy: off

artifacts:
  - path: dist
    name: xqemu
    type: zip
