# usb subsystem core
common-obj-y += core.o combined-packet.o bus.o desc.o
common-obj-y += libhw.o

# usb host adapters
common-obj-$(CONFIG_USB_OHCI) += hcd-ohci.o

# emulated usb devices
common-obj-y += dev-hub.o
common-obj-y += dev-hid.o

# usb pass-through
common-obj-y += $(patsubst %,host-%.o,$(HOST_USB))
