obj-y += gloffscreen_common.o
obj-$(CONFIG_WIN32) += gloffscreen_wgl.o
obj-$(CONFIG_LINUX) += gloffscreen_glx.o
obj-$(CONFIG_DARWIN) += gloffscreen_cgl.o
ifneq ($(CONFIG_DARWIN),y)
obj-$(CONFIG_BSD) += gloffscreen_glx.o
endif

