common-obj-$(CONFIG_SERIAL) += serial.o serial-isa.o
common-obj-$(CONFIG_SERIAL_PCI) += serial-pci.o
common-obj-$(CONFIG_VIRTIO) += virtio-console.o

common-obj-$(CONFIG_ISA_DEBUG) += debugcon.o

obj-$(CONFIG_VIRTIO) += virtio-serial-bus.o
