name: Build (macOS)

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        configuration: ["Debug", "Release"]
    steps:
    - name: Define Build Options
      shell: python
      run: |
        if "${{ matrix.configuration }}" == "Debug":
          print('Configuring for Debug')
          print('::set-env name=BUILD_PARAM::')
          print('::set-env name=ARTIFACT_NAME::xqemu-debug')
        else:
          print('Configuring for Release')
          print('::set-env name=BUILD_PARAM::--release')
          print('::set-env name=ARTIFACT_NAME::xqemu-release')
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        brew update
        brew unlink python@2
        brew install \
          pixman \
          sdl2 \
          libepoxy \
          coreutils \
          pkg-config \
          ccache
    - name: Initialize Compiler Cache
      id: cache
      uses: actions/cache@v1
      with:
        path: /tmp/xqemu-ccache
        key: cache-${{ runner.os }}-${{ matrix.configuration }}-${{ github.sha }}
        restore-keys: cache-${{ runner.os }}-${{ matrix.configuration }}-
    - name: Compile
      run: |
        export CCACHE_DIR=/tmp/xqemu-ccache
        export CCACHE_MAXSIZE=250M
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
        ./build.sh ${{ env.BUILD_PARAM }}
        echo -e "\nCompiler Cache Stats:"
        ccache -s -c
